logging:
  level:
    root: WARN
    springframework.web: WARN
    org.hibernate: ERROR
    com.example.demo: TRACE

    #pattern:
    # console: %clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n
    #console: '%clr(%d{HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(-){faint} %clr([%4.15t]){cyan} %clr(:){red} %clr(%m){faint}%n'

spring:
  datasource:
#    initialization-mode: always
    # MariaDB
#    username: root
#    password: 123
#    url: jdbc:mysql://192.168.42.133:3306/shop?useSSL=false
#    driver-class-name: org.mariadb.jdbc.Driver

    # HSQLDB
    username: admin
    password: changeme
    url: jdbc:hsqldb:file:/tmp/shop/shop.hsdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql

  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.HSQLDialect
    # ddl-auto available values: create-drop, update
    hibernate.ddl-auto: create-drop
    show-sql: false

#  h2:
#    console:
#      settings:
#        enabled: true
#        path: h2
#        web-allow-others: true

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

  http:
    converters:
      preferred-json-mapper: gson

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      wrap-exceptions: false

management:
  security:
    enabled: false

shop:
  users:
    password.strength: true
    email.check: true

  security:
    user.token.validity: 1200
    service.token.validity: 31556952