spring:
  data:
    mongodb:
      host: localhost
      port: 27017

  jpa:
    hibernate:
      ddl-auto: create

  redis:
    port: 6379
    embedded: true

mybatis:
  type-aliases-package: com.example.demo.mysql


logging:
  level:
    root: WARN
    springframework.web: DEBUG
    org.hibernate: ERROR
    com.example.demo.mysql: DEBUG

