spring:
  data:
    mongodb:
      host: localhost
      port: 27017

  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3307/test
    username: root
    password: 123456