spring:
  data:
    mongodb:
      host: localhost
      port: 27017

  jpa:
    hibernate:
      ddl-auto: create

  redis:
    port: 6379
    embedded: true

logging:
  level:
    root: WARN
    springframework.web: DEBUG
    org.hibernate: ERROR
