spring:
  data:
    mongodb:
      host: localhost
      port: 27017

  jpa:
    hibernate:
      ddl-auto: create

  redis:
    port: 6379
    embedded: true

  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
      enabled: true

mybatis:
  type-aliases-package: com.example.demo.mysql


logging:
  level:
    root: WARN
    springframework.web: DEBUG
    org.hibernate: ERROR
    com.example.demo.mysql: DEBUG

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
