package com.example.demo.mysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.NoSuchElementException;

@RestController    // This means that this class is a Controller
@RequestMapping(path = "/mybatis/user") // This means URL's start with /demo (after Application path)
public class UserMybatisController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserMapper userMapper;

    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser(@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userMapper.insert(n);
        return "Saved";
    }

    @GetMapping(path = "/list")
    public @ResponseBody
    Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userMapper.getAll();
    }

    @GetMapping(path = "/{id}")
    public User getById(@PathVariable Long id) {
        User u = userMapper.getOne(id);
        if (u == null) {
            throw new NoSuchElementException();
        } else {
            return u;
        }
    }
}
